title: My Coding Blog
author: Cbeg-76
email: Carl.Begert@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for HTML and CSS. I am starting out as well.
 Please comment if anyone can provide any help to new coders or users.
 All opinions are welcome and appreciated. Again thanks for stopping by!!

# social links
twitter_username: @BegertCarl
github_username:  Cbeg-76

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
